### PR TITLE
Fix BarePipeChainStart for ranges

### LINKED ISSUE #120: BarePipeChainStart incorrectly fails for ranges
```elixir
0..14 |> Enum.map(fn n -> n * 2 end)
```

### PR DESCRIPTION
**Pull request by rrrene**
Fixes #120 (also adds a test to ensure it stays fixed ^_^)

### CODE REVIEW

File: lib/dogma/rule/bare_pipe_chain_start.ex [hunk 1]
```diff
@@ -80,6 +80,10 @@ defmodule Dogma.Rule.BarePipeChainStart do
   defp function_line({:<<>>, _, _}),
   do: :ok
 
+  # exception for binaries
```
Comment (lpil) [inline lib/dogma/rule/bare_pipe_chain_start.ex]: For binaries? :)

Comment (rrrene) [inline lib/dogma/rule/bare_pipe_chain_start.ex]: Ahem ... yes? no? :sweat_smile:

**Comment by lpil** [comment]
Thanks! :)
